##Assignment 2

Q1. Creating and Inspecting NumPy Arrays
Create the following two NumPy arrays:

A = [10, 20, 30, 40, 50]

B = [
 [1, 2, 3],
 [4, 5, 6]
]

Using NumPy, display the following information for both arrays:

• The array itself.

• Number of dimensions using ndim.

• Shape using shape.

• Total number of elements using size.

• Data type using dtype.

In [2]:
import numpy as np
a = np.array([10,20,30,40,50])
b = np.array([[1,2,3],[4,5,6]])
print("The array itself")
print(a)
print(b)
print("Number of dimensions using ndim")
print(a.ndim)
print(b.ndim)
print("Shape using shape")
print(a.shape)
print(b.shape)
print("Total number of elements using size")
print(a.size)
print(b.size)
print("Data type using dtype")
print(a.dtype)
print(b.dtype)

The array itself
[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
Number of dimensions using ndim
1
2
Shape using shape
(5,)
(2, 3)
Total number of elements using size
5
6
Data type using dtype
int64
int64


## Q2. NumPy Array-Creation Functions

Create an array containing 20 elements using each of the following NumPy functions:

• np.arange()

• np.linspace()

• np.zeros()

• np.ones()

For each function:

• Display the resulting array.

• Specify the shape of the resulting array.

• Explain what the function does.

• Give one practical application where the function could be useful

In [3]:
a= np.arange(10,30,2)
print(a)
print("shape of a is : ",a.shape)

[10 12 14 16 18 20 22 24 26 28]
shape of a is :  (10,)


np.arrage() take usually three parameter first start then end and the third parameter is jump like if third parameter is 2 then start from 10 to 30 and jump 2 so output is 10,12,14,....,28

practical application of these is when we want to make a array of even elenment form 10 to 30

In [4]:
b = np.linspace(10,30,20)
print(b)

[10.         11.05263158 12.10526316 13.15789474 14.21052632 15.26315789
 16.31578947 17.36842105 18.42105263 19.47368421 20.52631579 21.57894737
 22.63157895 23.68421053 24.73684211 25.78947368 26.84210526 27.89473684
 28.94736842 30.        ]


"np.linespace take three parameneter first start and the second is end and third is how many point you want between start and end so linespace function convert the array from 10 to 30 equal space"

"when we want to divide in equal partation so use np.linespace "

In [5]:
c=np.zeros(20)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


"np.zero create the zero valued array for given parameter "

"np.zero use when we want to zero array for perticular range"

In [6]:
d=np.ones(20)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


"np.ones create the one valued array for given parameter "

"np.ones use when we want to one as elenment array for perticular range"

## Q3. NumPy Indexing and Slicing

Create the following matrix:

A = np.arange(1, 26).reshape(5, 5)

The resulting matrix will contain values from 1 to 25. Using only NumPy indexing, slicing, and Boolean masking,

perform the following operations:

• Extract the first row.

• Extract the last row.

• Extract the first column.

• Extract the last column.

• Extract the middle 3 × 3 matrix.

• Extract all even numbers.

• Extract all values greater than 15.

• Reverse the order of the rows.

• Reverse the order of the columns

In [7]:
a= np.arange(1,26).reshape(5,5)
print(a)

print("first row of array : ",a[:1,])
print("last row of array: ",a[len(a)-1:,])
print("first column :\n ",a[:,:1])
print("last column :\n",a[len(a)-1:,])
print("middle 3X3 : ",a[len(a)//2-1:len(a)//2+2,len(a)//2-1:len(a)//2+2])
print("all even numbers : \n",a[a%2==0])
print("all values greter then 15 ",a[a>15])
print("reverse the order of row \n",a[::-1])
print("reverse the order of column \n",a[:,::-1])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row of array :  [[1 2 3 4 5]]
last row of array:  [[21 22 23 24 25]]
first column :
  [[ 1]
 [ 6]
 [11]
 [16]
 [21]]
last column :
 [[21 22 23 24 25]]
middle 3X3 :  [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
all even numbers : 
 [ 2  4  6  8 10 12 14 16 18 20 22 24]
all values greter then 15  [16 17 18 19 20 21 22 23 24 25]
reverse the order of row 
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
reverse the order of column 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


## Q4. NumPy Data Types and Type Conversion

Create the following NumPy array:

A = np.array([10, 20, 30, 40, 50])

Convert the array sequentially into the following data types:

• int32

• float64

• int16

For each conversion:

• Display the array.

• Display its data type.

• Explain why data-type conversion may be useful in numerical computing.

In [8]:
a = np.array([10,20,30,40,50])
print("type of a : ",a.dtype)
print(a)
a_int = a.astype("int32")
print("type of a_int : ",a_int.dtype)
print(a_int)
a_float = a.astype("float64")
print("type of a_float : ",a_float.dtype)
print(a_float)

type of a :  int64
[10 20 30 40 50]
type of a_int :  int32
[10 20 30 40 50]
type of a_float :  float64
[10. 20. 30. 40. 50.]


data type conversion is a critical tool in the numerical computing because hardware has finit limit choosing the correct data tyape balancese computation speed memory consumption, and mathematical precision

## Q5. Array Reshaping

Create:

A = np.arange(1, 25)

Reshape this array into each of the following shapes:

• 2 × 12

• 3 × 8

• 4 × 6

• 6 × 4

For every resulting array:

• Display the matrix.

• Display its shape.

• Display its size.

In [9]:
a= np.arange(1,25)
b = a.reshape(2,12)
print("2 * 12 array :\n",b)
print("shape of b :",b.shape)
print("size of b :",b.size)
c = a.reshape(3,8)
print("3 * 8 array :\n",c)
print("shape of c :",c.shape)
print("size of c :",c.size)
d = a.reshape(4,6)
print("4 * 6 array :\n",d)
print("shape of d :",d.shape)
print("size of d :",d.size)
e = a.reshape(6,4)
print("6 * 4 array :\n",e)
print("shape of e :",e.shape)
print("size of e :",e.size)

2 * 12 array :
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
shape of b : (2, 12)
size of b : 24
3 * 8 array :
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
shape of c : (3, 8)
size of c : 24
4 * 6 array :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape of d : (4, 6)
size of d : 24
6 * 4 array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape of e : (6, 4)
size of e : 24


## Q6. Vectorized Student Marks Processing

Consider the following student marks:

marks = np.array([45, 67, 89, 32,76, 91, 55, 43])

The university has decided to provide 5 bonus marks to every student. Using

NumPy:

• Add 5 marks to every student.

• Ensure that no student's marks exceed 100.

• Calculate the average marks.

• Find the highest marks.

• Find the lowest marks.

• Find the number of students who scored at least 50 after adding the bonus.

In [10]:
marks = np.array([45, 67, 89, 32,76, 91, 55, 43])
print(np.clip(marks+5,0,100))
print("average marks : ",np.average(marks))
print("highest marks : ",np.max(marks))
print("lowest marks : ",np.min(marks))
print("number of students who scored at least 50 after adding the bonus : ",len(marks[marks+5>50]))

[50 72 94 37 81 96 60 48]
average marks :  62.25
highest marks :  91
lowest marks :  32
number of students who scored at least 50 after adding the bonus :  5


## Q7. Boolean Masking and Conditional Data Modification

Consider the following temperature dataset:

temperature = np.array([
 32, 28, 35, 40, 25,
 30, 42, 27, 38
])

Using NumPy Boolean masking:

• Extract all temperatures greater than 35.

• Extract temperatures between 28 and 38 inclusive.

• Count how many temperatures are greater than 35.

• Count how many temperatures are below 30.

• Replace every temperature greater than 40 with 40.

• Replace every temperature below 28 with 28.

• Display the final modified array.

In [11]:
temperature = np.array([ 32, 28, 35, 40, 25, 30, 42, 27, 38 ])

print("temperatures greater than 35 : ",temperature[temperature>35])
print("temperatures between 28 and 38 inclusive : ",temperature[(temperature>=28) & (temperature<=38)])
print("temperatures greater than 35 count : ",len(temperature[temperature>35]))
print("temperatures below 30 count : ",len(temperature[temperature<30]))
temperature[temperature>40]=40
temperature[temperature<28]=28

print("temperatures greater than 40 replaced with 40 and temperatures below 28 replaced with 28 : \n")
print(temperature)

temperatures greater than 35 :  [40 42 38]
temperatures between 28 and 38 inclusive :  [32 28 35 30 38]
temperatures greater than 35 count :  3
temperatures below 30 count :  3
temperatures greater than 40 replaced with 40 and temperatures below 28 replaced with 28 : 

[32 28 35 40 28 30 40 28 38]


## Q8. Statistical Analysis Using NumPy

Given:

data = np.array([
 12, 15, 18, 21,
 25, 30, 35, 40
])

Using NumPy, calculate:

• Mean

• Median


• Variance

• Standard deviation

• Minimum

• Maximum

• Range

• 25th percentile

• 50th percentile

• 75th percentile


In [12]:
data = np.array([12, 15, 18, 21,25, 30, 35, 40])
print("mean:",np.mean(data))
print("median:",np.median(data))
print("variance:",np.var(data))
print("standard deviation:",np.std(data))
print("minimum:",np.min(data))
print("maximum:",np.max(data))
print("range:",np.max(data)-np.min(data))
p25, p50, p75 = np.percentile(data, [25, 50, 75])
print(f"25th Percentile: ",p25)
print(f"50th Percentile (Median): ",p50)
print(f"75th Percentile:",p75)

mean: 24.5
median: 23.0
variance: 85.25
standard deviation: 9.233092656309694
minimum: 12
maximum: 40
range: 28
25th Percentile:  17.25
50th Percentile (Median):  23.0
75th Percentile: 31.25


## Q9. Broadcasting in NumPy

Consider:

A = np.array([
 [10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]
])

B = np.array([1, 2, 3])

Using NumPy broadcasting:

• Task 1: Add B to every row of A.

• Task 2: Multiply every row of A by B.

• Task 3: Subtract B from every row of A.

• Task 4: Divide every row of A by B.

Finally, explain:

• What is the shape of A?

• What is the shape of B?

• Why does broadcasting work here?

• What would happen if B had shape (2,) instead?


In [13]:
a = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
b=np.array([1, 2, 3])
t1=a+b
t2=a*b
t3=a-b
t4=a/b
print("add b to a :\n",t1)
print("multiply a by b :\n",t2)
print("subtract b from a :\n",t3)
print("divide a by b :\n",t4)
print("shape of a:",a.shape)
print("shape of b:",b.shape)
print("ans 3:Broadcasting works because the trailing dimensions are compatible")
print("ans 4:If B had a shape of (2,), the operations would crash and throw a ValueError")

add b to a :
 [[11 22 33]
 [41 52 63]
 [71 82 93]]
multiply a by b :
 [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]
subtract b from a :
 [[ 9 18 27]
 [39 48 57]
 [69 78 87]]
divide a by b :
 [[10. 10. 10.]
 [40. 25. 20.]
 [70. 40. 30.]]
shape of a: (3, 3)
shape of b: (3,)
ans 3:Broadcasting works because the trailing dimensions are compatible
ans 4:If B had a shape of (2,), the operations would crash and throw a ValueError


## Q10. Vectorized Grade Assignment

Given the following marks:

marks = np.array([
 35, 78, 92, 41,
 56, 29, 88, 67
])

Assign grades according to the following rules:

Marks Range Grade

90–100 A+

80–89 A

70–79 B

50–69 C

35–49 D

Below 35 F

Using NumPy:

• Create a grade array.

• Display each student's marks and corresponding grade.

• Count the number of students in each grade category.

In [14]:
marks = np.array([35, 78, 92, 41, 56, 29, 88, 67])
conditions = [(marks >= 90) & (marks <= 100),(marks >= 80) & (marks <= 89),(marks >= 70) & (marks <= 79),(marks >= 50) & (marks <= 69),(marks >= 35) & (marks <= 49),(marks < 35)]
choices = ['A+', 'A', 'B', 'C', 'D', 'F']
grades = np.select(conditions, choices, default='')
print("Student Grades:")
for mark, grade in zip(marks, grades):
    print(f"Mark: {mark} -> Grade: {grade}")
unique_grades, counts = np.unique(grades, return_counts=True)
grade_counts = dict(zip(unique_grades, counts))
print("\nGrade Category Counts:")
for grade in choices:
    print(f"Grade {grade}: {grade_counts.get(grade, 0)} student(s)")

Student Grades:
Mark: 35 -> Grade: D
Mark: 78 -> Grade: B
Mark: 92 -> Grade: A+
Mark: 41 -> Grade: D
Mark: 56 -> Grade: C
Mark: 29 -> Grade: F
Mark: 88 -> Grade: A
Mark: 67 -> Grade: C

Grade Category Counts:
Grade A+: 1 student(s)
Grade A: 1 student(s)
Grade B: 1 student(s)
Grade C: 2 student(s)
Grade D: 2 student(s)
Grade F: 1 student(s)
